openapi: "3.0.0"
info:
  version: 0.0.1
  title: Code Micro Videos
  description: A API to Code Micro Videos
  termsOfService: http://swagger.io/terms/
  contact:
    name: Selmison Miranda
    email: selmison@gmail.com
    url: http://github.com/selmison
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: https://{hostname}
    variables:
      hostname:
        default: localhost
paths:
  /categories:
    get:
      description: |
        Returns all categories from the system that the user has access to
      operationId: categoriesGet
      responses:
        '200':
          description: category response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Category'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      description: Creates a new category in the system. Duplicates are not allowed
      operationId: categoryCreate
      requestBody:
        description: Category to create in the store
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewCategory'
      responses:
        '201':
          description: category creation response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Category'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /categories/{name}:
    get:
      description: Returns a category based on a single name
      operationId: categoryGetByName
      parameters:
        - name: name
          in: path
          description: name of category to fetch
          required: true
          schema:
            type: string
      responses:
        '200':
          description: category response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Category'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      description: deletes a single category based on the name supplied
      operationId: categoryDelete
      parameters:
        - name: name
          in: path
          description: name of category to delete
          required: true
          schema:
            type: string
      responses:
        '204':
          description: category deleted
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Category:
      allOf:
        - $ref: '#/components/schemas/NewCategory'
        - type: object
          properties:
            id:
              type: string
              format: uuid

    NewCategory:
      type: object
      required:
        - name
      properties:
        name:
          type: string

    Error:
      type: object
      required:
        - slug
        - message
      properties:
        code:
          type: string
        message:
          type: string