// Package ports provides primitives to interact the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen DO NOT EDIT.
package ports

// Category defines model for Category.
type Category struct {
	// Embedded struct due to allOf(#/components/schemas/NewCategory)
	NewCategory
	// Embedded fields due to inline allOf schema
	Id *string `json:"id,omitempty"`
}

// Error defines model for Error.
type Error struct {
	Code    *string `json:"code,omitempty"`
	Message string  `json:"message"`
}

// NewCategory defines model for NewCategory.
type NewCategory struct {
	Name string `json:"name"`
}

// CategoryCreateJSONBody defines parameters for CategoryCreate.
type CategoryCreateJSONBody NewCategory

// CategoryCreateRequestBody defines body for CategoryCreate for application/json ContentType.
type CategoryCreateJSONRequestBody CategoryCreateJSONBody
