// Code generated by SQLBoiler 4.2.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	CastMembers    string
	Categories     string
	Genres         string
	GorpMigrations string
}{
	CastMembers:    "cast_members",
	Categories:     "categories",
	Genres:         "genres",
	GorpMigrations: "gorp_migrations",
}
