// Code generated by SQLBoiler 4.2.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	CastMembers    string
	Categories     string
	CategoryGenre  string
	CategoryVideo  string
	GenreVideo     string
	Genres         string
	GorpMigrations string
	Videos         string
}{
	CastMembers:    "cast_members",
	Categories:     "categories",
	CategoryGenre:  "category_genre",
	CategoryVideo:  "category_video",
	GenreVideo:     "genre_video",
	Genres:         "genres",
	GorpMigrations: "gorp_migrations",
	Videos:         "videos",
}
