// Code generated by SQLBoiler 4.2.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/null/v8"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// Video is an object representing the database table.
type Video struct {
	ID           string      `boil:"id" json:"id" toml:"id" yaml:"id"`
	Title        string      `boil:"title" json:"title" toml:"title" yaml:"title"`
	Description  string      `boil:"description" json:"description" toml:"description" yaml:"description"`
	YearLaunched int16       `boil:"year_launched" json:"year_launched" toml:"year_launched" yaml:"year_launched"`
	Opened       null.Bool   `boil:"opened" json:"opened,omitempty" toml:"opened" yaml:"opened,omitempty"`
	Rating       int16       `boil:"rating" json:"rating" toml:"rating" yaml:"rating"`
	Duration     int16       `boil:"duration" json:"duration" toml:"duration" yaml:"duration"`
	VideoFile    null.String `boil:"video_file" json:"video_file,omitempty" toml:"video_file" yaml:"video_file,omitempty"`
	CreatedAt    null.Time   `boil:"created_at" json:"created_at,omitempty" toml:"created_at" yaml:"created_at,omitempty"`
	UpdatedAt    null.Time   `boil:"updated_at" json:"updated_at,omitempty" toml:"updated_at" yaml:"updated_at,omitempty"`
	DeletedAt    null.Time   `boil:"deleted_at" json:"deleted_at,omitempty" toml:"deleted_at" yaml:"deleted_at,omitempty"`

	R *videoR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L videoL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var VideoColumns = struct {
	ID           string
	Title        string
	Description  string
	YearLaunched string
	Opened       string
	Rating       string
	Duration     string
	VideoFile    string
	CreatedAt    string
	UpdatedAt    string
	DeletedAt    string
}{
	ID:           "id",
	Title:        "title",
	Description:  "description",
	YearLaunched: "year_launched",
	Opened:       "opened",
	Rating:       "rating",
	Duration:     "duration",
	VideoFile:    "video_file",
	CreatedAt:    "created_at",
	UpdatedAt:    "updated_at",
	DeletedAt:    "deleted_at",
}

// Generated where

type whereHelpernull_Bool struct{ field string }

func (w whereHelpernull_Bool) EQ(x null.Bool) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, false, x)
}
func (w whereHelpernull_Bool) NEQ(x null.Bool) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, true, x)
}
func (w whereHelpernull_Bool) IsNull() qm.QueryMod    { return qmhelper.WhereIsNull(w.field) }
func (w whereHelpernull_Bool) IsNotNull() qm.QueryMod { return qmhelper.WhereIsNotNull(w.field) }
func (w whereHelpernull_Bool) LT(x null.Bool) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelpernull_Bool) LTE(x null.Bool) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelpernull_Bool) GT(x null.Bool) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelpernull_Bool) GTE(x null.Bool) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}

var VideoWhere = struct {
	ID           whereHelperstring
	Title        whereHelperstring
	Description  whereHelperstring
	YearLaunched whereHelperint16
	Opened       whereHelpernull_Bool
	Rating       whereHelperint16
	Duration     whereHelperint16
	VideoFile    whereHelpernull_String
	CreatedAt    whereHelpernull_Time
	UpdatedAt    whereHelpernull_Time
	DeletedAt    whereHelpernull_Time
}{
	ID:           whereHelperstring{field: "\"videos\".\"id\""},
	Title:        whereHelperstring{field: "\"videos\".\"title\""},
	Description:  whereHelperstring{field: "\"videos\".\"description\""},
	YearLaunched: whereHelperint16{field: "\"videos\".\"year_launched\""},
	Opened:       whereHelpernull_Bool{field: "\"videos\".\"opened\""},
	Rating:       whereHelperint16{field: "\"videos\".\"rating\""},
	Duration:     whereHelperint16{field: "\"videos\".\"duration\""},
	VideoFile:    whereHelpernull_String{field: "\"videos\".\"video_file\""},
	CreatedAt:    whereHelpernull_Time{field: "\"videos\".\"created_at\""},
	UpdatedAt:    whereHelpernull_Time{field: "\"videos\".\"updated_at\""},
	DeletedAt:    whereHelpernull_Time{field: "\"videos\".\"deleted_at\""},
}

// VideoRels is where relationship names are stored.
var VideoRels = struct {
	Categories string
	Genres     string
}{
	Categories: "Categories",
	Genres:     "Genres",
}

// videoR is where relationships are stored.
type videoR struct {
	Categories CategorySlice `boil:"Categories" json:"Categories" toml:"Categories" yaml:"Categories"`
	Genres     GenreSlice    `boil:"Genres" json:"Genres" toml:"Genres" yaml:"Genres"`
}

// NewStruct creates a new relationship struct
func (*videoR) NewStruct() *videoR {
	return &videoR{}
}

// videoL is where Load methods for each relationship are stored.
type videoL struct{}

var (
	videoAllColumns            = []string{"id", "title", "description", "year_launched", "opened", "rating", "duration", "video_file", "created_at", "updated_at", "deleted_at"}
	videoColumnsWithoutDefault = []string{"id", "title", "description", "year_launched", "rating", "duration", "video_file", "created_at", "updated_at", "deleted_at"}
	videoColumnsWithDefault    = []string{"opened"}
	videoPrimaryKeyColumns     = []string{"id"}
)

type (
	// VideoSlice is an alias for a slice of pointers to Video.
	// This should generally be used opposed to []Video.
	VideoSlice []*Video
	// VideoHook is the signature for custom Video hook methods
	VideoHook func(context.Context, boil.ContextExecutor, *Video) error

	videoQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	videoType                 = reflect.TypeOf(&Video{})
	videoMapping              = queries.MakeStructMapping(videoType)
	videoPrimaryKeyMapping, _ = queries.BindMapping(videoType, videoMapping, videoPrimaryKeyColumns)
	videoInsertCacheMut       sync.RWMutex
	videoInsertCache          = make(map[string]insertCache)
	videoUpdateCacheMut       sync.RWMutex
	videoUpdateCache          = make(map[string]updateCache)
	videoUpsertCacheMut       sync.RWMutex
	videoUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var videoBeforeInsertHooks []VideoHook
var videoBeforeUpdateHooks []VideoHook
var videoBeforeDeleteHooks []VideoHook
var videoBeforeUpsertHooks []VideoHook

var videoAfterInsertHooks []VideoHook
var videoAfterSelectHooks []VideoHook
var videoAfterUpdateHooks []VideoHook
var videoAfterDeleteHooks []VideoHook
var videoAfterUpsertHooks []VideoHook

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *Video) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range videoBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *Video) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range videoBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *Video) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range videoBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *Video) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range videoBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *Video) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range videoAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterSelectHooks executes all "after Select" hooks.
func (o *Video) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range videoAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *Video) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range videoAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *Video) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range videoAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *Video) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range videoAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddVideoHook registers your hook function for all future operations.
func AddVideoHook(hookPoint boil.HookPoint, videoHook VideoHook) {
	switch hookPoint {
	case boil.BeforeInsertHook:
		videoBeforeInsertHooks = append(videoBeforeInsertHooks, videoHook)
	case boil.BeforeUpdateHook:
		videoBeforeUpdateHooks = append(videoBeforeUpdateHooks, videoHook)
	case boil.BeforeDeleteHook:
		videoBeforeDeleteHooks = append(videoBeforeDeleteHooks, videoHook)
	case boil.BeforeUpsertHook:
		videoBeforeUpsertHooks = append(videoBeforeUpsertHooks, videoHook)
	case boil.AfterInsertHook:
		videoAfterInsertHooks = append(videoAfterInsertHooks, videoHook)
	case boil.AfterSelectHook:
		videoAfterSelectHooks = append(videoAfterSelectHooks, videoHook)
	case boil.AfterUpdateHook:
		videoAfterUpdateHooks = append(videoAfterUpdateHooks, videoHook)
	case boil.AfterDeleteHook:
		videoAfterDeleteHooks = append(videoAfterDeleteHooks, videoHook)
	case boil.AfterUpsertHook:
		videoAfterUpsertHooks = append(videoAfterUpsertHooks, videoHook)
	}
}

// OneG returns a single video record from the query using the global executor.
func (q videoQuery) OneG(ctx context.Context) (*Video, error) {
	return q.One(ctx, boil.GetContextDB())
}

// One returns a single video record from the query.
func (q videoQuery) One(ctx context.Context, exec boil.ContextExecutor) (*Video, error) {
	o := &Video{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for videos")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// AllG returns all Video records from the query using the global executor.
func (q videoQuery) AllG(ctx context.Context) (VideoSlice, error) {
	return q.All(ctx, boil.GetContextDB())
}

// All returns all Video records from the query.
func (q videoQuery) All(ctx context.Context, exec boil.ContextExecutor) (VideoSlice, error) {
	var o []*Video

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to Video slice")
	}

	if len(videoAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// CountG returns the count of all Video records in the query, and panics on error.
func (q videoQuery) CountG(ctx context.Context) (int64, error) {
	return q.Count(ctx, boil.GetContextDB())
}

// Count returns the count of all Video records in the query.
func (q videoQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count videos rows")
	}

	return count, nil
}

// ExistsG checks if the row exists in the table, and panics on error.
func (q videoQuery) ExistsG(ctx context.Context) (bool, error) {
	return q.Exists(ctx, boil.GetContextDB())
}

// Exists checks if the row exists in the table.
func (q videoQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if videos exists")
	}

	return count > 0, nil
}

// Categories retrieves all the category's Categories with an executor.
func (o *Video) Categories(mods ...qm.QueryMod) categoryQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.InnerJoin("\"category_video\" on \"categories\".\"id\" = \"category_video\".\"category_id\""),
		qm.Where("\"category_video\".\"video_id\"=?", o.ID),
	)

	query := Categories(queryMods...)
	queries.SetFrom(query.Query, "\"categories\"")

	if len(queries.GetSelect(query.Query)) == 0 {
		queries.SetSelect(query.Query, []string{"\"categories\".*"})
	}

	return query
}

// Genres retrieves all the genre's Genres with an executor.
func (o *Video) Genres(mods ...qm.QueryMod) genreQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.InnerJoin("\"genre_video\" on \"genres\".\"id\" = \"genre_video\".\"genre_id\""),
		qm.Where("\"genre_video\".\"video_id\"=?", o.ID),
	)

	query := Genres(queryMods...)
	queries.SetFrom(query.Query, "\"genres\"")

	if len(queries.GetSelect(query.Query)) == 0 {
		queries.SetSelect(query.Query, []string{"\"genres\".*"})
	}

	return query
}

// LoadCategories allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (videoL) LoadCategories(ctx context.Context, e boil.ContextExecutor, singular bool, maybeVideo interface{}, mods queries.Applicator) error {
	var slice []*Video
	var object *Video

	if singular {
		object = maybeVideo.(*Video)
	} else {
		slice = *maybeVideo.(*[]*Video)
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &videoR{}
		}
		args = append(args, object.ID)
	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &videoR{}
			}

			for _, a := range args {
				if a == obj.ID {
					continue Outer
				}
			}

			args = append(args, obj.ID)
		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.Select("\"categories\".*, \"a\".\"video_id\""),
		qm.From("\"categories\""),
		qm.InnerJoin("\"category_video\" as \"a\" on \"categories\".\"id\" = \"a\".\"category_id\""),
		qm.WhereIn("\"a\".\"video_id\" in ?", args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load categories")
	}

	var resultSlice []*Category

	var localJoinCols []string
	for results.Next() {
		one := new(Category)
		var localJoinCol string

		err = results.Scan(&one.ID, &one.Name, &one.Description, &one.IsValidated, &one.CreatedAt, &one.UpdatedAt, &localJoinCol)
		if err != nil {
			return errors.Wrap(err, "failed to scan eager loaded results for categories")
		}
		if err = results.Err(); err != nil {
			return errors.Wrap(err, "failed to plebian-bind eager loaded slice categories")
		}

		resultSlice = append(resultSlice, one)
		localJoinCols = append(localJoinCols, localJoinCol)
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on categories")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for categories")
	}

	if len(categoryAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.Categories = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &categoryR{}
			}
			foreign.R.Videos = append(foreign.R.Videos, object)
		}
		return nil
	}

	for i, foreign := range resultSlice {
		localJoinCol := localJoinCols[i]
		for _, local := range slice {
			if local.ID == localJoinCol {
				local.R.Categories = append(local.R.Categories, foreign)
				if foreign.R == nil {
					foreign.R = &categoryR{}
				}
				foreign.R.Videos = append(foreign.R.Videos, local)
				break
			}
		}
	}

	return nil
}

// LoadGenres allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (videoL) LoadGenres(ctx context.Context, e boil.ContextExecutor, singular bool, maybeVideo interface{}, mods queries.Applicator) error {
	var slice []*Video
	var object *Video

	if singular {
		object = maybeVideo.(*Video)
	} else {
		slice = *maybeVideo.(*[]*Video)
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &videoR{}
		}
		args = append(args, object.ID)
	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &videoR{}
			}

			for _, a := range args {
				if a == obj.ID {
					continue Outer
				}
			}

			args = append(args, obj.ID)
		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.Select("\"genres\".*, \"a\".\"video_id\""),
		qm.From("\"genres\""),
		qm.InnerJoin("\"genre_video\" as \"a\" on \"genres\".\"id\" = \"a\".\"genre_id\""),
		qm.WhereIn("\"a\".\"video_id\" in ?", args...),
		qmhelper.WhereIsNull("\"genres\".\"deleted_at\""),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load genres")
	}

	var resultSlice []*Genre

	var localJoinCols []string
	for results.Next() {
		one := new(Genre)
		var localJoinCol string

		err = results.Scan(&one.ID, &one.Name, &one.IsValidated, &one.CreatedAt, &one.UpdatedAt, &one.DeletedAt, &localJoinCol)
		if err != nil {
			return errors.Wrap(err, "failed to scan eager loaded results for genres")
		}
		if err = results.Err(); err != nil {
			return errors.Wrap(err, "failed to plebian-bind eager loaded slice genres")
		}

		resultSlice = append(resultSlice, one)
		localJoinCols = append(localJoinCols, localJoinCol)
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on genres")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for genres")
	}

	if len(genreAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.Genres = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &genreR{}
			}
			foreign.R.Videos = append(foreign.R.Videos, object)
		}
		return nil
	}

	for i, foreign := range resultSlice {
		localJoinCol := localJoinCols[i]
		for _, local := range slice {
			if local.ID == localJoinCol {
				local.R.Genres = append(local.R.Genres, foreign)
				if foreign.R == nil {
					foreign.R = &genreR{}
				}
				foreign.R.Videos = append(foreign.R.Videos, local)
				break
			}
		}
	}

	return nil
}

// AddCategoriesG adds the given related objects to the existing relationships
// of the video, optionally inserting them as new records.
// Appends related to o.R.Categories.
// Sets related.R.Videos appropriately.
// Uses the global database handle.
func (o *Video) AddCategoriesG(ctx context.Context, insert bool, related ...*Category) error {
	return o.AddCategories(ctx, boil.GetContextDB(), insert, related...)
}

// AddCategories adds the given related objects to the existing relationships
// of the video, optionally inserting them as new records.
// Appends related to o.R.Categories.
// Sets related.R.Videos appropriately.
func (o *Video) AddCategories(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*Category) error {
	var err error
	for _, rel := range related {
		if insert {
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		}
	}

	for _, rel := range related {
		query := "insert into \"category_video\" (\"video_id\", \"category_id\") values ($1, $2)"
		values := []interface{}{o.ID, rel.ID}

		if boil.IsDebug(ctx) {
			writer := boil.DebugWriterFrom(ctx)
			fmt.Fprintln(writer, query)
			fmt.Fprintln(writer, values)
		}
		_, err = exec.ExecContext(ctx, query, values...)
		if err != nil {
			return errors.Wrap(err, "failed to insert into join table")
		}
	}
	if o.R == nil {
		o.R = &videoR{
			Categories: related,
		}
	} else {
		o.R.Categories = append(o.R.Categories, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &categoryR{
				Videos: VideoSlice{o},
			}
		} else {
			rel.R.Videos = append(rel.R.Videos, o)
		}
	}
	return nil
}

// SetCategoriesG removes all previously related items of the
// video replacing them completely with the passed
// in related items, optionally inserting them as new records.
// Sets o.R.Videos's Categories accordingly.
// Replaces o.R.Categories with related.
// Sets related.R.Videos's Categories accordingly.
// Uses the global database handle.
func (o *Video) SetCategoriesG(ctx context.Context, insert bool, related ...*Category) error {
	return o.SetCategories(ctx, boil.GetContextDB(), insert, related...)
}

// SetCategories removes all previously related items of the
// video replacing them completely with the passed
// in related items, optionally inserting them as new records.
// Sets o.R.Videos's Categories accordingly.
// Replaces o.R.Categories with related.
// Sets related.R.Videos's Categories accordingly.
func (o *Video) SetCategories(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*Category) error {
	query := "delete from \"category_video\" where \"video_id\" = $1"
	values := []interface{}{o.ID}
	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, query)
		fmt.Fprintln(writer, values)
	}
	_, err := exec.ExecContext(ctx, query, values...)
	if err != nil {
		return errors.Wrap(err, "failed to remove relationships before set")
	}

	removeCategoriesFromVideosSlice(o, related)
	if o.R != nil {
		o.R.Categories = nil
	}
	return o.AddCategories(ctx, exec, insert, related...)
}

// RemoveCategoriesG relationships from objects passed in.
// Removes related items from R.Categories (uses pointer comparison, removal does not keep order)
// Sets related.R.Videos.
// Uses the global database handle.
func (o *Video) RemoveCategoriesG(ctx context.Context, related ...*Category) error {
	return o.RemoveCategories(ctx, boil.GetContextDB(), related...)
}

// RemoveCategories relationships from objects passed in.
// Removes related items from R.Categories (uses pointer comparison, removal does not keep order)
// Sets related.R.Videos.
func (o *Video) RemoveCategories(ctx context.Context, exec boil.ContextExecutor, related ...*Category) error {
	var err error
	query := fmt.Sprintf(
		"delete from \"category_video\" where \"video_id\" = $1 and \"category_id\" in (%s)",
		strmangle.Placeholders(dialect.UseIndexPlaceholders, len(related), 2, 1),
	)
	values := []interface{}{o.ID}
	for _, rel := range related {
		values = append(values, rel.ID)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, query)
		fmt.Fprintln(writer, values)
	}
	_, err = exec.ExecContext(ctx, query, values...)
	if err != nil {
		return errors.Wrap(err, "failed to remove relationships before set")
	}
	removeCategoriesFromVideosSlice(o, related)
	if o.R == nil {
		return nil
	}

	for _, rel := range related {
		for i, ri := range o.R.Categories {
			if rel != ri {
				continue
			}

			ln := len(o.R.Categories)
			if ln > 1 && i < ln-1 {
				o.R.Categories[i] = o.R.Categories[ln-1]
			}
			o.R.Categories = o.R.Categories[:ln-1]
			break
		}
	}

	return nil
}

func removeCategoriesFromVideosSlice(o *Video, related []*Category) {
	for _, rel := range related {
		if rel.R == nil {
			continue
		}
		for i, ri := range rel.R.Videos {
			if o.ID != ri.ID {
				continue
			}

			ln := len(rel.R.Videos)
			if ln > 1 && i < ln-1 {
				rel.R.Videos[i] = rel.R.Videos[ln-1]
			}
			rel.R.Videos = rel.R.Videos[:ln-1]
			break
		}
	}
}

// CreateGenresG adds the given related objects to the existing relationships
// of the video, optionally inserting them as new records.
// Appends related to o.R.Genres.
// Sets related.R.Videos appropriately.
// Uses the global database handle.
func (o *Video) CreateGenresG(ctx context.Context, insert bool, related ...*Genre) error {
	return o.CreateGenres(ctx, boil.GetContextDB(), insert, related...)
}

// CreateGenres adds the given related objects to the existing relationships
// of the video, optionally inserting them as new records.
// Appends related to o.R.Genres.
// Sets related.R.Videos appropriately.
func (o *Video) CreateGenres(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*Genre) error {
	var err error
	for _, rel := range related {
		if insert {
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		}
	}

	for _, rel := range related {
		query := "insert into \"genre_video\" (\"video_id\", \"genre_id\") values ($1, $2)"
		values := []interface{}{o.ID, rel.ID}

		if boil.IsDebug(ctx) {
			writer := boil.DebugWriterFrom(ctx)
			fmt.Fprintln(writer, query)
			fmt.Fprintln(writer, values)
		}
		_, err = exec.ExecContext(ctx, query, values...)
		if err != nil {
			return errors.Wrap(err, "failed to insert into join table")
		}
	}
	if o.R == nil {
		o.R = &videoR{
			Genres: related,
		}
	} else {
		o.R.Genres = append(o.R.Genres, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &genreR{
				Videos: VideoSlice{o},
			}
		} else {
			rel.R.Videos = append(rel.R.Videos, o)
		}
	}
	return nil
}

// SetGenresG removes all previously related items of the
// video replacing them completely with the passed
// in related items, optionally inserting them as new records.
// Sets o.R.Videos's Genres accordingly.
// Replaces o.R.Genres with related.
// Sets related.R.Videos's Genres accordingly.
// Uses the global database handle.
func (o *Video) SetGenresG(ctx context.Context, insert bool, related ...*Genre) error {
	return o.SetGenres(ctx, boil.GetContextDB(), insert, related...)
}

// SetGenres removes all previously related items of the
// video replacing them completely with the passed
// in related items, optionally inserting them as new records.
// Sets o.R.Videos's Genres accordingly.
// Replaces o.R.Genres with related.
// Sets related.R.Videos's Genres accordingly.
func (o *Video) SetGenres(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*Genre) error {
	query := "delete from \"genre_video\" where \"video_id\" = $1"
	values := []interface{}{o.ID}
	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, query)
		fmt.Fprintln(writer, values)
	}
	_, err := exec.ExecContext(ctx, query, values...)
	if err != nil {
		return errors.Wrap(err, "failed to remove relationships before set")
	}

	removeGenresFromVideosSlice(o, related)
	if o.R != nil {
		o.R.Genres = nil
	}
	return o.CreateGenres(ctx, exec, insert, related...)
}

// RemoveGenresG relationships from objects passed in.
// Removes related items from R.Genres (uses pointer comparison, removal does not keep order)
// Sets related.R.Videos.
// Uses the global database handle.
func (o *Video) RemoveGenresG(ctx context.Context, related ...*Genre) error {
	return o.RemoveGenres(ctx, boil.GetContextDB(), related...)
}

// RemoveGenres relationships from objects passed in.
// Removes related items from R.Genres (uses pointer comparison, removal does not keep order)
// Sets related.R.Videos.
func (o *Video) RemoveGenres(ctx context.Context, exec boil.ContextExecutor, related ...*Genre) error {
	var err error
	query := fmt.Sprintf(
		"delete from \"genre_video\" where \"video_id\" = $1 and \"genre_id\" in (%s)",
		strmangle.Placeholders(dialect.UseIndexPlaceholders, len(related), 2, 1),
	)
	values := []interface{}{o.ID}
	for _, rel := range related {
		values = append(values, rel.ID)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, query)
		fmt.Fprintln(writer, values)
	}
	_, err = exec.ExecContext(ctx, query, values...)
	if err != nil {
		return errors.Wrap(err, "failed to remove relationships before set")
	}
	removeGenresFromVideosSlice(o, related)
	if o.R == nil {
		return nil
	}

	for _, rel := range related {
		for i, ri := range o.R.Genres {
			if rel != ri {
				continue
			}

			ln := len(o.R.Genres)
			if ln > 1 && i < ln-1 {
				o.R.Genres[i] = o.R.Genres[ln-1]
			}
			o.R.Genres = o.R.Genres[:ln-1]
			break
		}
	}

	return nil
}

func removeGenresFromVideosSlice(o *Video, related []*Genre) {
	for _, rel := range related {
		if rel.R == nil {
			continue
		}
		for i, ri := range rel.R.Videos {
			if o.ID != ri.ID {
				continue
			}

			ln := len(rel.R.Videos)
			if ln > 1 && i < ln-1 {
				rel.R.Videos[i] = rel.R.Videos[ln-1]
			}
			rel.R.Videos = rel.R.Videos[:ln-1]
			break
		}
	}
}

// Videos retrieves all the records using an executor.
func Videos(mods ...qm.QueryMod) videoQuery {
	mods = append(mods, qm.From("\"videos\""), qmhelper.WhereIsNull("\"videos\".\"deleted_at\""))
	return videoQuery{NewQuery(mods...)}
}

// FindVideoG retrieves a single record by ID.
func FindVideoG(ctx context.Context, iD string, selectCols ...string) (*Video, error) {
	return FindVideo(ctx, boil.GetContextDB(), iD, selectCols...)
}

// FindVideo retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindVideo(ctx context.Context, exec boil.ContextExecutor, iD string, selectCols ...string) (*Video, error) {
	videoObj := &Video{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"videos\" where \"id\"=$1 and \"deleted_at\" is null", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, videoObj)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from videos")
	}

	return videoObj, nil
}

// InsertG a single record. See Insert for whitelist behavior description.
func (o *Video) InsertG(ctx context.Context, columns boil.Columns) error {
	return o.Insert(ctx, boil.GetContextDB(), columns)
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *Video) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no videos provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if queries.MustTime(o.CreatedAt).IsZero() {
			queries.SetScanner(&o.CreatedAt, currTime)
		}
		if queries.MustTime(o.UpdatedAt).IsZero() {
			queries.SetScanner(&o.UpdatedAt, currTime)
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(videoColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	videoInsertCacheMut.RLock()
	cache, cached := videoInsertCache[key]
	videoInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			videoAllColumns,
			videoColumnsWithDefault,
			videoColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(videoType, videoMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(videoType, videoMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"videos\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"videos\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into videos")
	}

	if !cached {
		videoInsertCacheMut.Lock()
		videoInsertCache[key] = cache
		videoInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// UpdateG a single Video record using the global executor.
// See Update for more documentation.
func (o *Video) UpdateG(ctx context.Context, columns boil.Columns) (int64, error) {
	return o.Update(ctx, boil.GetContextDB(), columns)
}

// Update uses an executor to update the Video.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *Video) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		queries.SetScanner(&o.UpdatedAt, currTime)
	}

	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	videoUpdateCacheMut.RLock()
	cache, cached := videoUpdateCache[key]
	videoUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			videoAllColumns,
			videoPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update videos, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"videos\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, videoPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(videoType, videoMapping, append(wl, videoPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update videos row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for videos")
	}

	if !cached {
		videoUpdateCacheMut.Lock()
		videoUpdateCache[key] = cache
		videoUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAllG updates all rows with the specified column values.
func (q videoQuery) UpdateAllG(ctx context.Context, cols M) (int64, error) {
	return q.UpdateAll(ctx, boil.GetContextDB(), cols)
}

// UpdateAll updates all rows with the specified column values.
func (q videoQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for videos")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for videos")
	}

	return rowsAff, nil
}

// UpdateAllG updates all rows with the specified column values.
func (o VideoSlice) UpdateAllG(ctx context.Context, cols M) (int64, error) {
	return o.UpdateAll(ctx, boil.GetContextDB(), cols)
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o VideoSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), videoPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"videos\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, videoPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in video slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all video")
	}
	return rowsAff, nil
}

// UpsertG attempts an insert, and does an update or ignore on conflict.
func (o *Video) UpsertG(ctx context.Context, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	return o.Upsert(ctx, boil.GetContextDB(), updateOnConflict, conflictColumns, updateColumns, insertColumns)
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *Video) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no videos provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if queries.MustTime(o.CreatedAt).IsZero() {
			queries.SetScanner(&o.CreatedAt, currTime)
		}
		queries.SetScanner(&o.UpdatedAt, currTime)
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(videoColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	videoUpsertCacheMut.RLock()
	cache, cached := videoUpsertCache[key]
	videoUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			videoAllColumns,
			videoColumnsWithDefault,
			videoColumnsWithoutDefault,
			nzDefaults,
		)
		update := updateColumns.UpdateColumnSet(
			videoAllColumns,
			videoPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert videos, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(videoPrimaryKeyColumns))
			copy(conflict, videoPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"videos\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(videoType, videoMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(videoType, videoMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if err == sql.ErrNoRows {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert videos")
	}

	if !cached {
		videoUpsertCacheMut.Lock()
		videoUpsertCache[key] = cache
		videoUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// DeleteG deletes a single Video record.
// DeleteG will match against the primary key column to find the record to delete.
func (o *Video) DeleteG(ctx context.Context, hardDelete bool) (int64, error) {
	return o.Delete(ctx, boil.GetContextDB(), hardDelete)
}

// Delete deletes a single Video record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *Video) Delete(ctx context.Context, exec boil.ContextExecutor, hardDelete bool) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no Video provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	var (
		sql  string
		args []interface{}
	)
	if hardDelete {
		args = queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), videoPrimaryKeyMapping)
		sql = "DELETE FROM \"videos\" WHERE \"id\"=$1"
	} else {
		currTime := time.Now().In(boil.GetLocation())
		o.DeletedAt = null.TimeFrom(currTime)
		wl := []string{"deleted_at"}
		sql = fmt.Sprintf("UPDATE \"videos\" SET %s WHERE \"id\"=$2",
			strmangle.SetParamNames("\"", "\"", 1, wl),
		)
		valueMapping, err := queries.BindMapping(videoType, videoMapping, append(wl, videoPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
		args = queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), valueMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from videos")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for videos")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

func (q videoQuery) DeleteAllG(ctx context.Context, hardDelete bool) (int64, error) {
	return q.DeleteAll(ctx, boil.GetContextDB(), hardDelete)
}

// DeleteAll deletes all matching rows.
func (q videoQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor, hardDelete bool) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no videoQuery provided for delete all")
	}

	if hardDelete {
		queries.SetDelete(q.Query)
	} else {
		currTime := time.Now().In(boil.GetLocation())
		queries.SetUpdate(q.Query, M{"deleted_at": currTime})
	}

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from videos")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for videos")
	}

	return rowsAff, nil
}

// DeleteAllG deletes all rows in the slice.
func (o VideoSlice) DeleteAllG(ctx context.Context, hardDelete bool) (int64, error) {
	return o.DeleteAll(ctx, boil.GetContextDB(), hardDelete)
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o VideoSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor, hardDelete bool) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(videoBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var (
		sql  string
		args []interface{}
	)
	if hardDelete {
		for _, obj := range o {
			pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), videoPrimaryKeyMapping)
			args = append(args, pkeyArgs...)
		}
		sql = "DELETE FROM \"videos\" WHERE " +
			strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, videoPrimaryKeyColumns, len(o))
	} else {
		currTime := time.Now().In(boil.GetLocation())
		for _, obj := range o {
			pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), videoPrimaryKeyMapping)
			args = append(args, pkeyArgs...)
			obj.DeletedAt = null.TimeFrom(currTime)
		}
		wl := []string{"deleted_at"}
		sql = fmt.Sprintf("UPDATE \"videos\" SET %s WHERE "+
			strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 2, videoPrimaryKeyColumns, len(o)),
			strmangle.SetParamNames("\"", "\"", 1, wl),
		)
		args = append([]interface{}{currTime}, args...)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from video slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for videos")
	}

	if len(videoAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// ReloadG refetches the object from the database using the primary keys.
func (o *Video) ReloadG(ctx context.Context) error {
	if o == nil {
		return errors.New("models: no Video provided for reload")
	}

	return o.Reload(ctx, boil.GetContextDB())
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *Video) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindVideo(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAllG refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *VideoSlice) ReloadAllG(ctx context.Context) error {
	if o == nil {
		return errors.New("models: empty VideoSlice provided for reload all")
	}

	return o.ReloadAll(ctx, boil.GetContextDB())
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *VideoSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := VideoSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), videoPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"videos\".* FROM \"videos\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, videoPrimaryKeyColumns, len(*o)) +
		"and \"deleted_at\" is null"

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in VideoSlice")
	}

	*o = slice

	return nil
}

// VideoExistsG checks if the Video row exists.
func VideoExistsG(ctx context.Context, iD string) (bool, error) {
	return VideoExists(ctx, boil.GetContextDB(), iD)
}

// VideoExists checks if the Video row exists.
func VideoExists(ctx context.Context, exec boil.ContextExecutor, iD string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"videos\" where \"id\"=$1 and \"deleted_at\" is null limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if videos exists")
	}

	return exists, nil
}
